name: app
description: RapidTest for your eyes.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^3.0.10
  get: ^3.4.3
  shared_preferences: ^0.5.8
  google_fonts: ^1.1.0
  simple_animations: ^2.2.1
  lottie: ^0.5.1
  firebase_ml_vision: ^0.9.6+2
  camera: ^0.5.8+5
  percent_indicator: ^2.1.5
  carousel_slider: ^2.2.1
  permission_handler: ^5.0.1+1
  flutter_svg: ^0.18.0
  wakelock: ^0.1.4+2
  intl: ^0.16.1
  firebase_analytics: ^6.0.0
  firebase_core: ^0.5.0
  advertising_id: ^1.0.0
  cloud_firestore: ^0.14.0+2
  firebase_messaging: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/OurRetina_512_300.png"
  adaptive_icon_background: "#98D4BB" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/OurRetina(Eye)_512_300.png" # only available for Android 8.0 devices and above

flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_intl:
  enabled: true
